variable "api_key" {}
variable "secret" {}
variable "env" {}
variable "service_account" {}
variable "aws_region" {}
variable "owner_email" {}
variable "owner" {}
variable "vpc_id" {}
variable "subnets_ids" {}
variable "route_table_id" {}
